### ISSUE TITLE
Data Leakage Issue

### ISSUE THREAD

**Issue by luke-ck** [SimonRaviv/VAE-QA#1]
Hi guys, 

first of all, great job on the model architecture, your approach is interesting. 

However, running the evaluation based on your splits, I noticed you did not take care to only take the unique reference images from LIVE (10 out of 29), so there are images from the train set that end up in the test set. For example, you train with [i05](https://github.com/SimonRaviv/VAE-QA/blob/c814845c349e27e0131dd0025e2c3ac211e1b961/datasets_splits/TID2013/seed_42/train_split.txt#L2162) from TID (bikes image in LIVE) and [test](https://github.com/SimonRaviv/VAE-QA/blob/c814845c349e27e0131dd0025e2c3ac211e1b961/datasets_splits/LIVE/seed_42/test_split.txt#L102) on the same bike image with the same distortion. I think the better approach would be to treat the overlap like in [here](https://github.com/ch-andrei/HDR-IQA-dom-adapt/blob/a9322db92cce5421acc00e4fb4a4e0f5f1311f88/data/datasets/upiq.py).

**Comment by SimonRaviv** [comment]
Hi @luke-ck,

Thanks!

We do make sure that each dataset split by reference images.
Do you mean it will be good to make sure the same image is not available in 2 different dataset train/test sets?

**Comment by luke-ck** [comment]
Hi, 

Yes, since the reference image content is the same, overlapping reference images should be assigned to one dataset or the other. You could assign them to TID2013 for example, so that you do not test on reference images seen during training.

**Comment by SimonRaviv** [comment]
I see.

We don't do this kind of separation on cross-dataset evaluation since it won't be comparable to other papers.

**Comment by luke-ck** [comment]
Alright I will close this issue then.
